### ISSUE TITLE
how to set another endpoint to another s3 compatible services ?

### ISSUE THREAD

**Issue by madruga8** [mediamonks/s3-batch-upload#21]
Hello,

the package is compatible with other s3 compatible services ?

thanks.

**Comment by ThaNarie** [comment]
Hi @madruga8,

I haven't tested this with other services besides S3, but if you create a new `Uploader` class, you can provide (undocumented and untested) your own `s3Client`, which is used like this:
https://github.com/mediamonks/s3-batch-upload/blob/master/src/lib/Uploader.ts#L64

Which makes use of the official S3 library:
https://www.npmjs.com/package/aws-sdk

So you can create a S3 client manually and configure it to your liking – if that supports setting custom endpoints, i guess that should work.

Or if alternative clients exist with a compatible API, that _could_ work as well.

Let me know your findings, or if you have any further questions!

**Comment by madruga8** [comment]
Hi ! thanks for the answer.

It worked very well with these parameters on blackblaze b2 bucket.

        config: { // or you can use a object
            accessKeyId: "xxxxxxxxxxxxx",
            secretAccessKey: "xxxxxxxxxxxxx",
            // region: "us-west-000",
            s3BucketEndpoint: true,
            endpoint: "https://my-bucket.s3.us-west-000.backblazeb2.com",
        },
        bucket: "my-bucket",

**Comment by ThaNarie** [comment]
Ah yes indeed, if you pass a config object, it will use that as well:
```
AWS.config.constructor(this.options.config);
```
So any config value from https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#constructor-property should work :)

Thanks for reporting back, and glad it worked out!
