### ISSUE TITLE
feature request: set access control to uploaded artefacts

### ISSUE THREAD

**Issue by YOU54F** [mediamonks/s3-batch-upload#3]
Hey,

It would be great to be able to set access control via the API, so that I can upload artefacts with public access, so that my consumers of the artefacts don't need to their AWS credentials to access the uploaded artefacts.

I will create a fork and see if I can make the changes requested in this issue and in #2 

Many thanks for the project! It meant I could refactor my script to not have to deal with using globby to get my files, and then iterating through them and reading them as a buffer.

These two feature requests would be the icing on the cake!

👌

**Comment by ThaNarie** [comment]
Looking forward to your fork/PR :) Let me know otherwise!

**Comment by YOU54F** [comment]
@ThaNarie ,  cheers dude. PR raised, let me know your thoughts 👌
